### ISSUE TITLE
[Bug]: value range checking from jsonargparse doesn't work

### ISSUE THREAD

**Issue by HYLcool** [modelscope/data-juicer#186]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

all

### Installation Method 安装方式

from source

### Data-Juicer Version Data-Juicer版本

latest

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

Although data-juicer uses jsonargparse to check the value range of arguments for OPs, it doesn't work now.

For example, if I set the min_score of language_id_score_filter to 100, jsonargparse will parse the arguments even if it's out of range and data-juicer will process the dataset, which is unexpected.
```python
# definition of LanguageIDScoreFilter
class LanguageIDScoreFilter(Filter):
    def __init__(self,
                 lang: Union[str, List[str], Tuple[str]] = '',
                 min_score: ClosedUnitInterval = 0.8,  # use ClosedUnitInterval to limit the value range of min_score to [0, 1]
                 *args,
                 **kwargs):
        ......
```
```yaml
process:
  - language_id_score_filter:
      lang: en
      min_score: 100  # out of range, but it will be parsed by jsonargparse as normal.
```

### To Reproduce 如何复现

Config file:
```yaml
# config file: test.yaml
# global parameters
project_name: 'demo-process'
dataset_path: './demos/data/demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './outputs/demo-process/demo-processed.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'zh'
      min_score: 100

```

And run it with:
```shell
dj-process --config test.yaml
```

### Configs 配置信息

See above.

### Logs 报错日志

Dataset is processed normally, which is unexpected.
