### ISSUE TITLE
Request a sample code demonstrating the use of image_captioning_from_gpt4v_mapper.py

### ISSUE THREAD

**Issue by Notonion** [modelscope/data-juicer#262]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

Do you have a sample code demonstrating the use of image_captioning_from_gpt4v_mapper.py? What should be the input?

**Comment by chenhesen** [comment]
Hi, the usage of this operator is similar to other mapper operators. You just need to add the operator to your configuration file and provide the appropriate parameters. 
e.g:
```yaml
# Process config example for dataset
# global parameters
project_name: 'demo-dedup'
dataset_path: ''  # path to your dataset directory or file
np: 1  # number of subprocess to process your dataset`
export_path: ''  # path to processed result dataset. Supported suffixes include ['jsonl', 'json', 'parquet']

# process schedule: a list of several process operators with their arguments
process:
  - image_captioning_from_gpt4v_mapper:                     # generate samples whose texts are generated based on gpt-4-visison and the image
      mode: 'description'                                     # mode of text generated from images, can be one of ['resoning', 'description', 'conversation', 'custom']
      api_key: ''                                             # the API key to authenticate the request
      max_token: 500                                          # the maximum number of tokens to generate. Default is 500.
      temperature: 1.0                                        # controls the randomness of the output (range from 0 to 1). Default is 0.
      system_prompt: ''                                       # a string prompt used to set the context of a conversation and provide global guidance or rules for the gpt4-vision so that it can  generate responses in the expected way. If `mode` set to `custom`, the parameter will be used
      user_prompt: ''                                         # a string prompt to guide the generation of gpt4-vision for each samples. It's "" in default, which means no prompt provided
      user_prompt_key: null                                   # the key name of fields in samples to store prompts for each sample. It's used for set different prompts for different samples. If it's none, use prompt in parameter "prompt". It's None in default
      keep_original_sample: true                              # whether to keep the original sample. If it's set to False, there will be only generated text in the final datasets and the original text will be removed. It's True in default
      any_or_all: 'any'                                       # keep this sample with 'any' or 'all' strategy of all images. 'any': keep this sample if any images meet the condition. 'all': keep this sample only if all images meet the condition
```
