### ISSUE TITLE
[Question] Can't find evalutor.yaml on the path of `/workspace/data-juicer/demos`

### ISSUE THREAD

**Issue by BenWu11** [modelscope/data-juicer#298]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

您好，
我想请问关于启动自动化评测相关问题。

如下图，我要执行指令中需要用到 `evalutor.yaml`，
但是我在`/workspace/data-juicer/demos`却找不到这个档案:
`python evaluator.py --config /workspace/data-juicer/demos/evalutor.yaml --begin-iteration 2000 --end-iteration 200000 --interation-interval 2000 --check-interval 30`

![image](https://github.com/modelscope/data-juicer/assets/142816339/6bb18eb0-7491-4d37-ac36-a932e03b641d)

**Comment by pan-x-c** [comment]
You can refer to this [document](https://github.com/modelscope/data-juicer/blob/main/tools/evaluator/README_ZH.md). For example:

```yaml
auto_eval:
  project_name: <str> # your project name
  model_name: <str>   # your model name
  cache_dir: <str>    # path of cache dir
  megatron:
    process_num: <int>     # number of process to run megatron
    megatron_home: <str>   # root dir of Megatron-LM
    checkpoint_path: <str> # path of checkpoint dir
    tokenizer_type: <str>  # support gpt2 or sentencepiece for now
    vocab_path: <str>      # configuration for gpt2 tokenizer type, path to vocab file
    merge_path: <str>      # configuration for gpt2 tokenizer type, path to merge file
    tokenizer_path: <str>  # configuration for sentencepiece tokenizer type, path to model file
    max_tokens: <int>      # max tokens to generate in inference
    token_per_iteration: <float> # billions tokens per iteraion
  helm:
    helm_spec_template_path: <str> # path of helm spec template file, default is tools/evaluator/config/helm_spec_template.conf
    helm_output_path: <str>  # path of helm output dir
    helm_env_name: <str>     # helm conda env name
```
