### ISSUE TITLE
How to speed up the processing speed of image-text similarity filtering？

### ISSUE THREAD

**Issue by qyx1121** [modelscope/data-juicer#363]
I use the image_text_similarity_filter, and set the parameters as follows:
```
 - image_text_similarity_filter:  
      hf_clip: openai/clip-vit-large-patch14                   
      min_score: 0.20315419
      mem_required: '30GB'
```
I am currently using two V100-32G GPUs, but despite having them, only two threads are running and the GPU memory usage is minimal. How can I enhance my computing efficiency?
<img width="591" alt="企业微信截图_5e939a24-0e16-442a-8b00-7de0d86dcf33" src="https://github.com/user-attachments/assets/1b0b1538-bc6e-40a2-a17e-a7e0f84f4104">
<img width="887" alt="企业微信截图_e3167225-a7ba-4964-8293-ca1b792d321d" src="https://github.com/user-attachments/assets/296df8ec-29ab-4385-99b2-420457045e3f">

By the way, if I do not specify 'mem_required', I am able to utilize more processes. However, this will result in OOM
