### ISSUE TITLE
[Bug]: 去重的hash计算卡在100%上，一直不过滤

### ISSUE THREAD

**Issue by xiafeng-nb** [modelscope/data-juicer#387]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

pip

### Data-Juicer Version Data-Juicer版本

latest

### Python Version Python版本

3.10

### Describe the bug 描述这个bug

昨天用7月份的代码处理redpajama的cc数据还能正常运行，今天拉了版最新代码后再运行会一直卡在document_simhash_deduplicator_compute_hash (num_proc=10): 100%|##########| 776770/776770 [04:52<00:00, 358.93 examples/s]
我处理的数据是单个jsonl文件，开启了10个np
![image](https://github.com/user-attachments/assets/6a52c36d-b671-4052-9c7f-45dfa1f101ad)

### To Reproduce 如何复现

python tools/process_data.py --config configs/data_juicer_recipes/redpajama-cc-2023-06-refine.yaml

### Configs 配置信息
```yaml
# global parameters
project_name: 'Data-Juicer-recipes-cc-2023-06'
dataset_path: '/redpajama-cc'  # path to your dataset directory or file
export_path: '/djdata/dj_en_head_0000.jsonl'

np: 10 # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments

process:
  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4

  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.7508  # 3sigma
      max_ratio: 0.8591  # 3sigma -- 1036821
  - average_line_length_filter:  # for code
      max_len: 1500  # < 3sigma -- 395868
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3  # > 3sigma -- 195026
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.0015  # 3sigma -- 287896
  - language_id_score_filter:  # remove language filter
      min_score: 0.793  # 3sigma -- 2173246
  - maximum_line_length_filter:  # for code
      max_len: 5000  # < 3sigma -- 797111
  - perplexity_filter:
      lang: en
      max_ppl: 5000  # 3sigma -- 942162
  - special_characters_filter:
      min_ratio: 0.15  # > 3sigma
      max_ratio: 0.35  # > 3sigma -- 1155090
  - text_length_filter:
      max_len: 58187  # 3sigma -- 1165902
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20
      max_num: 11529  # 3sigma -- 1185363
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.2962  # 3sigma -- 2407282
```
