### ISSUE TITLE
运行 python tools/process_data.py --config configs/demo/process.yaml 报错

### ISSUE THREAD

**Issue by wqdta** [modelscope/data-juicer#602]
### Question

环境：
windows10
anaconda 虚拟环境
python3.10.16

源码安装，初始化完成后执行
python tools/process_data.py --config configs/demo/process.yaml
报错：

![Image](https://github.com/user-attachments/assets/e7d6a96b-cf46-4864-8a40-9fd395888051)

**Comment by HYLcool** [comment]
嗨 @wqdta ，感谢你的关注与使用！

我们目前没有在Windows系统上进行过测试，因此Data-Juicer暂时不能保证在windows下完美运行。

根据报错截图，这是monitor在windows系统下获取GPU信息出错导致的，你可以试下在配置文件中添加一行`open_monitor: false`来停用monitor模块。

```yaml
# Process config example for dataset

# global parameters
project_name: 'demo-process'
dataset_path: './demos/data/demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './outputs/demo-process/demo-processed.jsonl'

####### 添加这一行
open_monitor: false
####### 添加这一行

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'zh'
      min_score: 0.8

```

如还有进一步问题，可随时交流~
