### ISSUE TITLE
dj 算子运行时有参数支持显示 CPU 数和内存么

### ISSUE THREAD

**Issue by xiedeyantu** [modelscope/data-juicer#716]
### Search before continuing 先搜索，再继续

- [x] I have searched the Data-Juicer issues and found no similar feature requests. 我已经搜索了 Data-Juicer 的 issue 列表但是没有发现类似的功能需求。

### Description 描述

想限制 CPU使用数和内存数

### Are you willing to submit a PR for this feature? 您是否乐意为此功能提交一个 PR？

- [ ] Yes I'd like to help by submitting a PR! 是的！我愿意提供帮助并提交一个PR！

**Comment by HYLcool** [comment]
嗨，你可以为单个OP设置参数cpu_required和mem_required来指定该算子预期会使用的CPU数和内存，如：
```yaml
process:
  - language_id_score_filter:
      lang: 'zh'
      min_score: 0.8
      cpu_required: 4
      mem_required: '16GB'
```
